function generateReport() {
  const type = document.getElementById("type").value;
  const platform = document.getElementById("platform").value;
  const desc = document.getElementById("desc").value.trim();

  if (!desc) {
    alert("Please enter incident description.");
    return;
  }

  const date = new Date().toLocaleString();

  const report = `
INCIDENT REPORT
========================
Type      : ${type}
Platform  : ${platform}
Date      : ${date}

Description:
${desc}

------------------------
Generated by NETSHELT
Cybersecurity Awareness Tool
Made by Tanmay Patil (Webytyrex)
`;

  document.getElementById("reportText").innerText = report;
  document.getElementById("outputCard").style.display = "block";

  // Optional: count reports
  if (typeof incrementStat === "function") {
    incrementStat("incidentReports");
  }
}

function copyReport() {
  const text = document.getElementById("reportText").innerText;
  navigator.clipboard.writeText(text);
  alert("Report copied to clipboard");
}
